# Generated by Django 6.0 on 2025-12-28 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название звена цепи поставки', max_length=50, verbose_name='Название звена цепи поставки')),
                ('email', models.EmailField(help_text='Email завода', max_length=254, verbose_name='Email завода')),
                ('country', models.CharField(help_text='Страна, где находится звено цепи поставок', max_length=50, verbose_name='Страна, где находится звено цепи поставок')),
                ('city', models.CharField(help_text='Город, где находится звено цепи поставок', max_length=100, verbose_name='Город, где находится звено цепи поставок')),
                ('street', models.CharField(help_text='Улица, на которой находится звено цепи поставок', max_length=100, verbose_name='Улица, на которой находится звено цепи поставок')),
                ('house_number', models.CharField(help_text='Номер дома, на которой находится звено цепи поставок', max_length=10, verbose_name='Номер дома, на которой находится звено цепи поставок')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text=' Выставляется автоматически при создании.', verbose_name='Дата создания звена цепи поставок')),
            ],
            options={
                'verbose_name': 'Завод',
                'verbose_name_plural': 'Заводы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название продукта', max_length=50, verbose_name='Название продукта')),
                ('model', models.CharField(help_text='Модель продукта', max_length=100, verbose_name='Модель продукта')),
                ('release_date', models.DateField(help_text='Формат: "ГГГГ-ММ-ДД"', verbose_name='Дата выхода продукта на рынок')),
                ('price', models.DecimalField(decimal_places=2, help_text='Формат: "12.34"', max_digits=20, verbose_name='Цена продукта')),
                ('produced_by', models.ForeignKey(blank=True, help_text='Завод, который произвел этот продукт', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_products', to='retail_chain.factory', verbose_name='Завод, который произвел этот продукт')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='SupplyChainNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название звена цепи поставки', max_length=50, verbose_name='Название звена цепи поставки')),
                ('email', models.EmailField(help_text='Email завода', max_length=254, verbose_name='Email завода')),
                ('country', models.CharField(help_text='Страна, где находится звено цепи поставок', max_length=50, verbose_name='Страна, где находится звено цепи поставок')),
                ('city', models.CharField(help_text='Город, где находится звено цепи поставок', max_length=100, verbose_name='Город, где находится звено цепи поставок')),
                ('street', models.CharField(help_text='Улица, на которой находится звено цепи поставок', max_length=100, verbose_name='Улица, на которой находится звено цепи поставок')),
                ('house_number', models.CharField(help_text='Номер дома, на которой находится звено цепи поставок', max_length=10, verbose_name='Номер дома, на которой находится звено цепи поставок')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text=' Выставляется автоматически при создании.', verbose_name='Дата создания звена цепи поставок')),
                ('supply_chain_role', models.CharField(choices=[('retail_network', 'Розничная сеть'), ('sole_proprietor', 'Индивидуальный предприниматель')], help_text='Варианты:\nfactory - завод(supplier будет отсутствовать),\nretail_network - розничная сеть,\nsole_proprietor - индивидуальный предприниматель.', max_length=50, verbose_name='Тип звена цепи поставок')),
                ('supplier_type', models.CharField(choices=[('factory', 'Завод'), ('another_node', 'Другие звенья цепи поставок')], help_text='Тип поставщика.\nВарианты:\n"factory" - завод,\n"another_node" - другие звенья цепи поставок (розничная сеть или ИП).', verbose_name='Поставщик')),
                ('supplier_id', models.PositiveIntegerField(help_text='Id поставщика', verbose_name='Id поставщика')),
                ('debt', models.DecimalField(decimal_places=2, default=0, help_text='Формат: "12.34". Обновление недоступно через API.', max_digits=20, verbose_name='Долг перед поставщиком')),
                ('products', models.ManyToManyField(help_text='id продуктов. Формат: [1, 2, 3,...].', related_name='supply_nodes', to='retail_chain.product', verbose_name='Продукты, которые были получены от поставщика')),
            ],
            options={
                'verbose_name': 'Звено цепи поставок',
                'verbose_name_plural': 'Звенья цепи поставок',
            },
        ),
    ]
