# Generated by Django 6.0 on 2025-12-27 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название продукта', max_length=50, verbose_name='Название продукта')),
                ('model', models.CharField(help_text='Модель продукта', max_length=100, verbose_name='Модель продукта')),
                ('release_date', models.DateField(help_text='Дата выхода продукта на рынок. Формат: ГГГГ-ММ-ДД', verbose_name='Дата выхода продукта на рынок')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена продукта', max_digits=20, verbose_name='Цена продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='SupplyChainNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название звена цепи поставки', max_length=50, verbose_name='Название звена цепи поставки')),
                ('supply_chain_role', models.CharField(choices=[('factory', 'Завод'), ('retail_network', 'Розничная сеть'), ('sole_proprietor', 'Индивидуальный предприниматель')], help_text='Тип звена цепи поставок. Варианты: factory - завод, retail_network - розничная сеть или sole_proprietor - индивидуальный предприниматель.', max_length=50, verbose_name='Тип звена цепи поставок')),
                ('email', models.EmailField(help_text='Email звена цепи поставок', max_length=254, verbose_name='Email звена цепи поставок')),
                ('country', models.CharField(help_text='Страна, где находится звено цепи поставок', max_length=50, verbose_name='Страна, где находится звено цепи поставок')),
                ('city', models.CharField(help_text='Город, где находится звено цепи поставок', max_length=100, verbose_name='Город, где находится звено цепи поставок')),
                ('street', models.CharField(help_text='Улица, на которой находится звено цепи поставок', max_length=100, verbose_name='Улица, на которой находится звено цепи поставок')),
                ('house_number', models.CharField(help_text='Номер дома, на которой находится звено цепи поставок', max_length=10, verbose_name='Номер дома, на которой находится звено цепи поставок')),
                ('debt', models.DecimalField(decimal_places=2, default=0, help_text='долг перед поставщиком. Сумма до копеек.', max_digits=20, verbose_name='Долг перед поставщиком')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='Дата создания звена цепи поставок. Выставляется автоматически при создании.', verbose_name='Дата создания звена цепи поставок')),
                ('chain_level', models.IntegerField(help_text='Уровень в иерархии поставок. Количество поставщиков от завода.', verbose_name='Уровень в иерархии поставок')),
                ('products', models.ManyToManyField(help_text='id продуктов', related_name='supply_nodes', to='retail_chain.product', verbose_name='Продукты, которые были получены от поставщика')),
                ('supplier', models.ForeignKey(help_text='id поставщика', on_delete=django.db.models.deletion.DO_NOTHING, related_name='node_supplier', to='retail_chain.supplychainnode', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Звено цепи поставок',
                'verbose_name_plural': 'Звенья цепи поставок',
            },
        ),
    ]
