# Generated by Django 6.0 on 2025-12-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Формат: 12.34', max_digits=20, verbose_name='Цена продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateField(help_text='Формат: ГГГГ-ММ-ДД', verbose_name='Дата выхода продукта на рынок'),
        ),
        migrations.AlterField(
            model_name='supplychainnode',
            name='supply_chain_role',
            field=models.CharField(choices=[('factory', 'Завод'), ('retail_network', 'Розничная сеть'), ('sole_proprietor', 'Индивидуальный предприниматель')], help_text='Тип звена цепи поставок.\nВарианты: factory - завод,\nretail_network - розничная сеть\nили sole_proprietor - индивидуальный предприниматель.', max_length=50, verbose_name='Тип звена цепи поставок'),
        ),
    ]
