# Generated by Django 6.0 on 2025-12-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplychainnode',
            name='supply_chain_role',
            field=models.CharField(choices=[('retail_network', 'Розничная сеть'), ('sole_proprietor', 'Индивидуальный предприниматель')], help_text='Варианты:\nretail_network - розничная сеть,\nsole_proprietor - индивидуальный предприниматель.', max_length=50, verbose_name='Тип звена цепи поставок'),
        ),
    ]
