# Generated by Django 6.0 on 2025-12-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_chain', '0002_alter_product_price_alter_product_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Формат: "12.34"', max_digits=20, verbose_name='Цена продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateField(help_text='Формат: "ГГГГ-ММ-ДД"', verbose_name='Дата выхода продукта на рынок'),
        ),
        migrations.AlterField(
            model_name='supplychainnode',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text=' Выставляется автоматически при создании.', verbose_name='Дата создания звена цепи поставок'),
        ),
        migrations.AlterField(
            model_name='supplychainnode',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Формат: "12.34"', max_digits=20, verbose_name='Долг перед поставщиком'),
        ),
        migrations.AlterField(
            model_name='supplychainnode',
            name='supply_chain_role',
            field=models.CharField(choices=[('factory', 'Завод'), ('retail_network', 'Розничная сеть'), ('sole_proprietor', 'Индивидуальный предприниматель')], help_text='Варианты:\nfactory - завод,\nretail_network - розничная сеть,\nsole_proprietor - индивидуальный предприниматель.', max_length=50, verbose_name='Тип звена цепи поставок'),
        ),
    ]
