# Generated by Django 6.0 on 2025-12-27 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_chain', '0003_alter_product_price_alter_product_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplychainnode',
            name='chain_level',
            field=models.IntegerField(blank=True, help_text='Уровень в иерархии поставок. Количество поставщиков от завода.', null=True, verbose_name='Уровень в иерархии поставок'),
        ),
        migrations.AlterField(
            model_name='supplychainnode',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='id поставщика. Если supply_chain_role "factory" - supplier автоматически null', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='node_supplier', to='retail_chain.supplychainnode', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='supplychainnode',
            name='supply_chain_role',
            field=models.CharField(choices=[('factory', 'Завод'), ('retail_network', 'Розничная сеть'), ('sole_proprietor', 'Индивидуальный предприниматель')], help_text='Варианты:\nfactory - завод(supplier будет),\nretail_network - розничная сеть,\nsole_proprietor - индивидуальный предприниматель.', max_length=50, verbose_name='Тип звена цепи поставок'),
        ),
    ]
