# Generated by Django 6.0 on 2025-12-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_chain', '0004_alter_supplychainnode_chain_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplychainnode',
            name='chain_level',
            field=models.IntegerField(default=0, help_text='Уровень в иерархии поставок. Количество поставщиков от завода.', verbose_name='Уровень в иерархии поставок'),
        ),
        migrations.AlterField(
            model_name='supplychainnode',
            name='supply_chain_role',
            field=models.CharField(choices=[('factory', 'Завод'), ('retail_network', 'Розничная сеть'), ('sole_proprietor', 'Индивидуальный предприниматель')], help_text='Варианты:\nfactory - завод(supplier будет отсутствовать),\nretail_network - розничная сеть,\nsole_proprietor - индивидуальный предприниматель.', max_length=50, verbose_name='Тип звена цепи поставок'),
        ),
    ]
