# Generated by Django 6.0 on 2025-12-27 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_chain', '0005_alter_supplychainnode_chain_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplychainnode',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Формат: "12.34". Обновление недоступно через API.', max_digits=20, verbose_name='Долг перед поставщиком'),
        ),
        migrations.AlterField(
            model_name='supplychainnode',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='id поставщика. Если supply_chain_role "factory" - supplier автоматически null', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_supplier', to='retail_chain.supplychainnode', verbose_name='Поставщик'),
        ),
    ]
